### ISSUE TITLE
[Question] Can be used for NetzNoe ?

### ISSUE THREAD

**Issue by Noschvie** [dbeinder/han-mosquito#1]
Hallo David
bin auf der Suche nach einer Hardware, die die beiden Zähler von NetzNoe unterstützen: externe Power Supply und MBus Interface. Als Firmware möchte ich gerne Tasmota verwenden.
Habe einen ESP32 und das M-Bus Slave Click Board mit Tasmota laufen, soweit ok.
Aber eine kompakte Hardware wie deine wäre mir lieber
mfg
Norbert

**Comment by dbeinder** [comment]
@Noschvie Siehe mein Kommentar im anderen Thread: https://github.com/UtilitechAS/amsreader-firmware/discussions/480#discussioncomment-5282325
Ich denke dein MA309 funktioniert mit meiner HW direkt bus-powered, egal was die NetzNoe Spezifikation meint. Andere Meter eher nur mit USB Supply, dazu kann man eine Leiterbahn auf dem PCB durchtrennen um den MBUS nicht zu belasten.

Tasmota sollte schon möglich sein, müsstest du allerdings selbst anpassen. Am RX Pin darf die Firmware keinen Pullup konfigurieren, sonst kommen die Daten nicht richtig an.

Ich habe vor kurzem einige produzieren lassen:
![panel(1)](https://user-images.githubusercontent.com/342955/234837384-dd8bcc59-4c91-4d21-b3d1-55f3d78f4bea.jpg)

Ich kann dir gerne welche zuschicken, sagen wir inkl. Versand 35€ für 1 Stk, +15€ für jedes weitere. 
Privatverkauf, Bastellösung, keine Gewährleistung, etc ;)
Bei Interesse einfach per Mail an `david (at) beinder.at`
